### ISSUE TITLE
Workspace, Session, Focus Refinements

### ISSUE THREAD

**Issue by gotjoshua** [gotjoshua/atom-textual-velocity#3]
- [x] start session with tree view hidden - via [viddo's custom init](https://github.com/viddo/atom-textual-velocity/blob/master/docs/recommended-usage/.atom/init.coffee#L10).
   - [x] open default folder for notes as project folder in new window
      - [x] optional via package settings
- [x] focus on search field (currently ctrl-L but only when session workspace window is already active)
   - [x] automatically after after closing a text editor in the pane

**Comment by viddo** [comment]
Hey, just want to give heads up in case you had plan to implement this and send a PR later, to save you from unnecessary work; I don't think it makes sense to include this inside the package out of the box because:

- It's not trivial how to handle these use case if the package is opened in multiple atom windows. 
- There's no good UI to set a global shortcut, the config types and preferences view is too limited.
- Everyone's workflow is different, so what works for me (or you) might not be what other people want

This is why I added a init config example and the [recommended usage docs](https://github.com/viddo/atom-textual-velocity/blob/master/docs/recommended-usage/) instead. See https://github.com/viddo/atom-textual-velocity/blob/master/docs/recommended-usage/.atom/init.coffee in case you had not already seen it. 

Also, if you intend to maintain a fork you might run into code conflicts further ahead, as the internals are likely to change a lot (until I'm done with v1).

**Comment by gotjoshua** [comment]
thanks for the heads up @viddo !
I found your recommended usage docs and solved most of my wishes with them.
Still I wanted to have the option to open the notes folder as the project for the active workspace.
and
i like the behavior that if i search, find and open a note.... then close it again, my focus goes back up to the search (like cmd-L)
Feel free to have a look at my commits on [3-session-refinements](https://github.com/gotjoshua/atom-textual-velocity/tree/3-session-refinements) 
I am curious what you think about the strategy.

Together with [the qq hack](https://github.com/gotjoshua/atom-textual-velocity/commit/a220f702f6e70af1313cb992a8b6f86b41c38e46) - it gets real useful as a "what was that command again?" tool

**Comment by viddo** [comment]
IMHO, these are very specific requests and minor modifications that would be better of in the init config. Unless there are a significant amount of users requesting these particular things, of course.

> i like the behavior that if i search, find and open a note.... then close it again, my focus goes back up to the search (like cmd-L)

I like this idea. 👍  Created an issue to get feedback from others first though: https://github.com/viddo/atom-textual-velocity/issues/47 I have some others things I want to attend first.

As mentioned there, you can make it easier by having a a single listener in the workspace, no need for individual listeners:

```js
atom.workspace.onDidDestroyPaneItem(function() {
  atom.commands.dispatch(atom.views.getView(atom.workspace), 'textual-velocity:focus-on-search')
})
```
